### ISSUE TITLE
Price Round Error

### ISSUE THREAD

**Issue by Efealtan0909** [V0xelTech/KristedShop#3]
if price set less than 1 it rounds it down to 0 which makes it empty the entire storage system if purchase with any payment happens.

**Comment by aporvv** [comment]
duplicate

**Comment by Efealtan0909** [comment]
no yours is duplicate

**Comment by aporvv** [comment]
no your mom is duplicate

**Comment by Efealtan0909** [comment]
shut

**Comment by aporvv** [comment]
no u

**Comment by qrmcat** [comment]
This one is alot better worded, I'll deem the other one duplicate.

**Comment by qrmcat** [comment]
This is working as intended, it sets the price to 0 when it is set below 0.01. I'll add a config option to set how many decimal digits is wanted

**Comment by qrmcat** [comment]
Fix is implemented in dev branch!
